name: Deploy EC2 instance to AWS

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        working-directory:  IaC
        run: terraform init -backend-config="bucket=appsilon-task" -backend-config="key=appsilon-terraform.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Plan
        working-directory: IaC
        run: terraform plan -out=tfplan -lock=false

      - name: Terraform Apply
        working-directory: IaC
        run: terraform apply tfplan -lock=false

      - name: Save Terraform state file to S3
        working-directory: IaC
        run: |
          aws s3 cp terraform.tfstate s3://appsilon-task/terraform.tfstate
